spring:
  cloud:
    function:
      definition: acmeResourcesOpsAutohaulWorkOrderCompleteV1TrainIdConsumer
    stream:
      bindings:
        acmeResourcesOpsAutohaulWorkOrderCompleteV1TrainIdConsumer-in-0:
          destination: acmeResources/ops/autohaul/workOrderComplete/v1/*
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: 'localhost:55555'
                msgVpn: default
                clientUsername: default
                clientPassword: default
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'

